### ISSUE TITLE
Google tag manager installation

### ISSUE THREAD

**Issue by OlgaShulezhko** [mikulaskafka/the-chocolate-shop-olga#1]
**Please install the tag manager code:**

1. Paste this code as high in the <head> of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PFNK65VW');</script>

2. Paste this code immediately after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PFNK65VW"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by mikulaskafka** [comment]
Installed as advised.

1. The following script was pasted as high on the page as possible:
`<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-PFNK65VW');</script>`

2. The following code was pasted immediately after the opening tag:
`<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PFNK65VW" height="0" width="0" style="display:none;visibility:hidden"></iframe>`

index.html

**Comment by OlgaShulezhko** [comment]
thank you!

**Comment by OlgaShulezhko** [comment]
Please move this script to <head> on each page of the website:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-PFNK65VW');</script>

![Screen Shot 2024-03-14 at 2 48 03 PM](https://github.com/mikulaskafka/the-chocolate-shop-olga/assets/162993220/52dccfb4-b9f7-4d3d-936f-598d96ce5441)

**Comment by mikulaskafka** [comment]
I understand now. It was updated on every page.
Please check if it's correct now and once you're happy with it, close the issue below, please.

**Comment by OlgaShulezhko** [comment]
I think so! thank you :)
