### ISSUE TITLE
group nav bar links in a separate class

### ISSUE THREAD

**Issue by OlgaShulezhko** [mikulaskafka/the-chocolate-shop-olga#2]
Hi! Could you please group the links in the navigation bar into one class in html and give it a name, so I can track the clicks on them separately in GA. Included: Home, Our Chocolates, About us, Reviews, Contact.

![Screen Shot 2024-03-15 at 11 15 25 AM](https://github.com/mikulaskafka/the-chocolate-shop-olga/assets/162993220/dfac5888-1697-4159-b374-b7403ecad913)

![Screen Shot 2024-03-15 at 11 20 48 AM](https://github.com/mikulaskafka/the-chocolate-shop-olga/assets/162993220/2a11e38d-6b2a-4e1c-82d9-6805caf8f130)

Thank you! :)

**Comment by mikulaskafka** [comment]
I added the following class to every item on every page:

`nav-item` (as in navigation-item)

I also added a distinct ID to every item, in case it'd be helpful

**Comment by mikulaskafka** [comment]
<img width="495" alt="Screenshot 2024-03-15 at 11 29 35" src="https://github.com/mikulaskafka/the-chocolate-shop-olga/assets/149764581/82a6a92e-08a0-4c9b-8118-7e5400fef24f">

**Comment by OlgaShulezhko** [comment]
thank you! everything works
